CREATE DATABASE CONTROLVUELO
GO

USE CONTROLVUELO
GO

CREATE TABLE tblAEROPUERTO
(CODIGO VARCHAR(10) PRIMARY KEY,
NOMBRE VARCHAR(30),
CIUDAD VARCHAR(30),
PAIS VARCHAR(30))

CREATE TABLE tblTELAEROPUERTO
(CODIGO_AEROPUERTO VARCHAR(10),
TELEFONO_AEROPUERTO SMALLINT,
PRIMARY KEY(CODIGO_AEROPUERTO, TELEFONO_AEROPUERTO))

CREATE TABLE tblLINEA_AEREA
(CODIGO VARCHAR(10) PRIMARY KEY,
NOMBRE VARCHAR(30),
PAIS VARCHAR(30))

CREATE TABLE tblPILOTO
(ID VARCHAR(10) PRIMARY KEY,
NOMBRE VARCHAR(30),
DIRECCION VARCHAR(30),
CIUDAD_RESIDENCIA VARCHAR(30),
CODIGO_LINEA VARCHAR(10),
COD_USUARIO INT,
TELEFONO VARCHAR(20))


CREATE TABLE tblAVION
(CODIGO VARCHAR(10) PRIMARY KEY,
MODELO VARCHAR(20),
CAPACIDAD INT,
CODIGO_LINEA VARCHAR(10))

CREATE TABLE tblVUELO
(CODIGO VARCHAR(10) PRIMARY KEY,
FECHA_partida VARCHAR(10),
FECHA_llegada VARCHAR(10),
PLAZAS_VACIAS INT,
IDPILOTO VARCHAR(10))

CREATE TABLE tblPROGRAMA_VUELO
(CODIGO VARCHAR(10) PRIMARY KEY,
CODIGO_VUELO VARCHAR(10),
CODIGO_LINEA VARCHAR(10),
DIAS_VUELO VARCHAR(30),
CODIGO_ESCALATECNICA VARCHAR(10),
AEROPUERTO_PARTIDA VARCHAR(10),
AEROPUERTO_DESTINO VARCHAR(10))

CREATE TABLE tblESCALA_TECNICA
(CODIGO VARCHAR(10) PRIMARY KEY,
COD_AEROPUERTO VARCHAR(10))

CREATE TABLE tblLINEA_AEROPUERTO
(CODIGO_AEROPUERTO VARCHAR(10),
CODIGO_LINEA VARCHAR(10),
PRIMARY KEY (CODIGO_AEROPUERTO, CODIGO_LINEA))

CREATE TABLE tblPROGRAMAVUELO_ESCALATECNICA(
CODIGO_PROGRAMAVUELO VARCHAR(10),
CODIGO_ESCALATECNICA VARCHAR(10),
PRIMARY KEY(CODIGO_PROGRAMAVUELO, CODIGO_ESCALATECNICA) 
)

CREATE TABLE tblUSUARIO (
CODIGO_USUARIO INT IDENTITY PRIMARY KEY,
NOMBRE_USUARIO VARCHAR(10),
CLAVE_USUARIO VARCHAR  (10),
ROL_USUARIO VARCHAR(5)
)

CREATE TABLE tblPERSONA
(ID VARCHAR(10) PRIMARY KEY,
NOMBRE VARCHAR(30),
CIUDAD VARCHAR(30),
COD_USUARIO INT)


GO

ALTER TABLE tblPERSONA ADD FOREIGN KEY (COD_USUARIO) REFERENCES tblUSUARIO(CODIGO_USUARIO)
ALTER TABLE tblPILOTO ADD FOREIGN KEY (COD_USUARIO) REFERENCES tblUSUARIO(CODIGO_USUARIO)
ALTER TABLE tblPILOTO ADD FOREIGN KEY (CODIGO_LINEA) REFERENCES tblLINEA_AEREA(CODIGO)
ALTER TABLE tblVUELO ADD FOREIGN KEY (IDPILOTO) REFERENCES tblPILOTO(ID)
ALTER TABLE tblAVION ADD FOREIGN KEY (CODIGO_LINEA) REFERENCES tblLINEA_AEREA(CODIGO)
ALTER TABLE tblTELPILOTO ADD FOREIGN KEY (IDPILOTO) REFERENCES tblPILOTO(ID)
ALTER TABLE tblTELAEROPUERTO ADD FOREIGN KEY (CODIGO_AEROPUERTO) REFERENCES tblAEROPUERTO(CODIGO)
ALTER TABLE tblLINEA_AEROPUERTO ADD FOREIGN KEY (CODIGO_AEROPUERTO) REFERENCES tblAEROPUERTO(CODIGO)
ALTER TABLE tblLINEA_AEROPUERTO ADD FOREIGN KEY (CODIGO_LINEA) REFERENCES tblLINEA_AEREA(CODIGO)
ALTER TABLE tblESCALA_TECNICA ADD FOREIGN KEY (COD_AEROPUERTO) REFERENCES tblAEROPUERTO(CODIGO)
ALTER TABLE tblPROGRAMA_VUELO ADD FOREIGN KEY (CODIGO_VUELO) REFERENCES tblVUELO(CODIGO)
ALTER TABLE tblPROGRAMA_VUELO ADD FOREIGN KEY (CODIGO_LINEA) REFERENCES tblLINEA_AEREA(CODIGO)
ALTER TABLE tblPROGRAMA_VUELO ADD FOREIGN KEY (CODIGO_ESCALATECNICA) REFERENCES tblESCALA_TECNICA(CODIGO)
ALTER TABLE tblPROGRAMA_VUELO ADD FOREIGN KEY (AEROPUERTO_PARTIDA) REFERENCES tblAEROPUERTO(CODIGO)
ALTER TABLE tblPROGRAMA_VUELO ADD FOREIGN KEY (AEROPUERTO_DESTINO) REFERENCES tblAEROPUERTO(CODIGO)
ALTER TABLE tblPROGRAMAVUELO_ESCALATECNICA ADD FOREIGN KEY (CODIGO_PROGRAMAVUELO) REFERENCES tblPROGRAMA_VUELO(CODIGO)
ALTER TABLE tblPROGRAMAVUELO_ESCALATECNICA ADD FOREIGN KEY (CODIGO_ESCALATECNICA) REFERENCES tblESCALA_TECNICA(CODIGO)


GO

create proc SP_ValidarCredencialesDeAcceso (
@usuario VARCHAR(10),
@clave VARCHAR(10))
AS
BEGIN
	IF EXISTS (SELECT nombre_usuario, clave_usuario FROM tblUSUARIO WHERE nombre_usuario = @usuario AND clave_usuario = @clave)
	BEGIN
		SELECT '0' as SW
	END
	ELSE
		BEGIN
			SELECT '1' as SW
		END
END
GO

CREATE PROCEDURE SP_CrearUsuario
@NOMBRE_USUARIO VARCHAR(10),
@CLAVE_USUARIO VARCHAR  (10),
@ROL_USUARIO VARCHAR(5)
AS
BEGIN
	IF EXISTS(SELECT CODIGO_USUARIO FROM tblUSUARIO WHERE NOMBRE_USUARIO = @NOMBRE_USUARIO)
	BEGIN				
		SELECT '0' AS SW,
			   'El nombre de usuario ya existe'
	END
	ELSE
	BEGIN
		INSERT INTO tblUSUARIO(NOMBRE_USUARIO, CLAVE_USUARIO, ROL_USUARIO) VALUES(@NOMBRE_USUARIO, @CLAVE_USUARIO, @ROL_USUARIO)

		SELECT '1' AS SW,
			   'Registro creado correctamente'
	END
END
GO

CREATE PROCEDURE SP_CrearPersona
@ID VARCHAR(10),
@NOMBRE VARCHAR(30),
@CIUDAD VARCHAR(30),
@COD_USUARIO INT
AS
BEGIN
	INSERT INTO tblPERSONA(ID, NOMBRE, CIUDAD,COD_USUARIO) VALUES(@ID, @NOMBRE, @CIUDAD,@COD_USUARIO)

		SELECT '1' AS SW,
			   'Registro creado correctamente'
END
GO

CREATE PROCEDURE SP_CrearPiloto
@ID VARCHAR(10),
@NOMBRE VARCHAR(30),
@DIRECCION VARCHAR(30),
@CIUDAD_RESIDENCIA VARCHAR(30),
@CODIGO_LINEA VARCHAR(10),
@COD_USUARIO INT,
@TELEFONO VARCHAR(20)
AS
BEGIN
	INSERT INTO tblPILOTO(ID, NOMBRE, DIRECCION,CIUDAD_RESIDENCIA, CODIGO_LINEA, COD_USUARIO, TELEFONO) VALUES(@ID, @NOMBRE, @DIRECCION,@CIUDAD_RESIDENCIA, @CODIGO_LINEA, @COD_USUARIO, @TELEFONO)

		SELECT '1' AS SW,
			   'Registro creado correctamente'
END
GO

CREATE PROCEDURE SP_ConsultarIdUsuario
@NOMBRE_USUARIO VARCHAR(10)
AS
BEGIN
	SELECT CODIGO_USUARIO	   
	FROM tblUSUARIO
	WHERE NOMBRE_USUARIO = @NOMBRE_USUARIO

END
GO



INSERT INTO tblUsuario VALUES ('sebas','1','A')
INSERT INTO tblLINEA_AEREA VALUES ('1','LA','COLOMBIA')

exec SP_ValidarCredencialesDeAcceso @usuario = 'sebas', @clave = '1'

exec SP_CrearUsuario @NOMBRE_USUARIO = 'sebas3435', @CLAVE_USUARIO='1', @ROL_USUARIO='A'

exec SP_ConsultarIdUsuario @nombre_usuario = 'sebas3435'

exec SP_CrearPiloto @ID = '1', @NOMBRE = 'DonPiloto', @DIRECCION = 'Cra 10',@CIUDAD_RESIDENCIA = 'Medellín', @CODIGO_LINEA = '1', @COD_USUARIO = 9 , @TELEFONO = '2341672'

select * from tblpersona
select * from tblusuario
select * from tblpiloto



