CREATE DATABASE CONTROLVUELO
GO
USE CONTROLVUELO
GO

/******* ------------------------------ CREACION DE TABLAS ------------------------------ *******/
CREATE TABLE tblAEROPUERTO
(CODIGO VARCHAR(10) PRIMARY KEY,
NOMBRE VARCHAR(30),
CIUDAD VARCHAR(30),
PAIS VARCHAR(30),
ID_RESPONSABLE VARCHAR(10),
ESTADO VARCHAR(50))

CREATE TABLE tblLINEA_AEREA
(CODIGO VARCHAR(10) PRIMARY KEY,
NOMBRE VARCHAR(30),
PAIS VARCHAR(30))

CREATE TABLE tblPILOTO
(ID VARCHAR(10) PRIMARY KEY,
NOMBRE VARCHAR(30),
DIRECCION VARCHAR(30),
CIUDAD_RESIDENCIA VARCHAR(30),
CODIGO_LINEA VARCHAR(10),
COD_USUARIO INT,
TELEFONO VARCHAR(20))

CREATE TABLE tblAVION
(CODIGO VARCHAR(10) PRIMARY KEY,
MODELO VARCHAR(20),
CAPACIDAD INT,
CODIGO_LINEA VARCHAR(10))

CREATE TABLE tblVUELO
(CODIGO VARCHAR(10) PRIMARY KEY,
FECHA_partida SMALLDATETIME,
FECHA_llegada SMALLDATETIME,
PLAZAS_VACIAS INT,
IDPILOTO VARCHAR(10),
COD_AVION VARCHAR(10))

CREATE TABLE tblPROGRAMA_VUELO
(CODIGO VARCHAR(10) PRIMARY KEY,
CODIGO_VUELO VARCHAR(10),
CODIGO_LINEA VARCHAR(10),
CODIGO_ESCALATECNICA VARCHAR(10),
AEROPUERTO_PARTIDA VARCHAR(10),
AEROPUERTO_DESTINO VARCHAR(10))

CREATE TABLE tblESCALA_TECNICA
(CODIGO VARCHAR(10) PRIMARY KEY,
COD_AEROPUERTO VARCHAR(10))

CREATE TABLE tblLINEA_AEROPUERTO
(CODIGO_AEROPUERTO VARCHAR(10),
CODIGO_LINEA VARCHAR(10),
PRIMARY KEY (CODIGO_AEROPUERTO, CODIGO_LINEA))

CREATE TABLE tblPROGRAMAVUELO_ESCALATECNICA(
CODIGO_PROGRAMAVUELO VARCHAR(10),
CODIGO_ESCALATECNICA VARCHAR(10),
PRIMARY KEY(CODIGO_PROGRAMAVUELO, CODIGO_ESCALATECNICA) 
)

CREATE TABLE tblUSUARIO (
CODIGO_USUARIO INT IDENTITY PRIMARY KEY,
NOMBRE_USUARIO VARCHAR(10),
CLAVE_USUARIO VARCHAR  (10),
ROL_USUARIO VARCHAR(5)
)

CREATE TABLE tblPERSONA
(ID VARCHAR(10) PRIMARY KEY,
NOMBRE VARCHAR(30),
CIUDAD VARCHAR(30),
COD_USUARIO INT)


GO

/******* ------------------------------ RELACION DE LAS TABLAS  ------------------------------ *******/
ALTER TABLE tblAEROPUERTO ADD FOREIGN KEY (ID_RESPONSABLE) REFERENCES tblPERSONA(ID)
ALTER TABLE tblPERSONA ADD FOREIGN KEY (COD_USUARIO) REFERENCES tblUSUARIO(CODIGO_USUARIO)
ALTER TABLE tblPILOTO ADD FOREIGN KEY (COD_USUARIO) REFERENCES tblUSUARIO(CODIGO_USUARIO)
ALTER TABLE tblPILOTO ADD FOREIGN KEY (CODIGO_LINEA) REFERENCES tblLINEA_AEREA(CODIGO)
ALTER TABLE tblVUELO ADD FOREIGN KEY (IDPILOTO) REFERENCES tblPILOTO(ID)
ALTER TABLE tblVUELO ADD FOREIGN KEY (COD_AVION) REFERENCES tblAVION(CODIGO)
ALTER TABLE tblAVION ADD FOREIGN KEY (CODIGO_LINEA) REFERENCES tblLINEA_AEREA(CODIGO)
ALTER TABLE tblLINEA_AEROPUERTO ADD FOREIGN KEY (CODIGO_AEROPUERTO) REFERENCES tblAEROPUERTO(CODIGO)
ALTER TABLE tblLINEA_AEROPUERTO ADD FOREIGN KEY (CODIGO_LINEA) REFERENCES tblLINEA_AEREA(CODIGO)
ALTER TABLE tblESCALA_TECNICA ADD FOREIGN KEY (COD_AEROPUERTO) REFERENCES tblAEROPUERTO(CODIGO)
ALTER TABLE tblPROGRAMA_VUELO ADD FOREIGN KEY (CODIGO_VUELO) REFERENCES tblVUELO(CODIGO)
ALTER TABLE tblPROGRAMA_VUELO ADD FOREIGN KEY (CODIGO_LINEA) REFERENCES tblLINEA_AEREA(CODIGO)
ALTER TABLE tblPROGRAMA_VUELO ADD FOREIGN KEY (CODIGO_ESCALATECNICA) REFERENCES tblESCALA_TECNICA(CODIGO)
ALTER TABLE tblPROGRAMA_VUELO ADD FOREIGN KEY (AEROPUERTO_PARTIDA) REFERENCES tblAEROPUERTO(CODIGO)
ALTER TABLE tblPROGRAMA_VUELO ADD FOREIGN KEY (AEROPUERTO_DESTINO) REFERENCES tblAEROPUERTO(CODIGO)
ALTER TABLE tblPROGRAMAVUELO_ESCALATECNICA ADD FOREIGN KEY (CODIGO_PROGRAMAVUELO) REFERENCES tblPROGRAMA_VUELO(CODIGO)
ALTER TABLE tblPROGRAMAVUELO_ESCALATECNICA ADD FOREIGN KEY (CODIGO_ESCALATECNICA) REFERENCES tblESCALA_TECNICA(CODIGO)


GO

/*******------------------------------ PROCEDIMIENTOS ALMACENADOS ------------------------------*******/
CREATE PROCEDURE SP_ValidarCredencialesDeAcceso (
@usuario VARCHAR(10),
@clave VARCHAR(10))
AS
BEGIN
	IF EXISTS (SELECT nombre_usuario, clave_usuario FROM tblUSUARIO WHERE nombre_usuario = @usuario AND clave_usuario = @clave)
	BEGIN
		SELECT '0' as SW
	END
	ELSE
		BEGIN
			SELECT '1' as SW
		END
END
GO

CREATE PROCEDURE SP_CrearUsuario
@NOMBRE_USUARIO VARCHAR(10),
@CLAVE_USUARIO VARCHAR  (10),
@ROL_USUARIO VARCHAR(5)
AS
BEGIN
	IF EXISTS(SELECT CODIGO_USUARIO FROM tblUSUARIO WHERE NOMBRE_USUARIO = @NOMBRE_USUARIO)
	BEGIN				
		SELECT '0' AS SW,
			   'El nombre de usuario ya existe'
	END
	ELSE
	BEGIN
		INSERT INTO tblUSUARIO(NOMBRE_USUARIO, CLAVE_USUARIO, ROL_USUARIO) VALUES(@NOMBRE_USUARIO, @CLAVE_USUARIO, @ROL_USUARIO)

		SELECT '1' AS SW,
			   'Registro creado correctamente'
	END
END
GO

CREATE PROCEDURE SP_CrearPersona
@ID VARCHAR(10),
@NOMBRE VARCHAR(30),
@CIUDAD VARCHAR(30),
@COD_USUARIO INT
AS
BEGIN
	INSERT INTO tblPERSONA(ID, NOMBRE, CIUDAD,COD_USUARIO) VALUES(@ID, @NOMBRE, @CIUDAD,@COD_USUARIO)

		SELECT '1' AS SW,
			   'Registro creado correctamente'
END
GO

CREATE PROCEDURE SP_CrearPiloto
@ID VARCHAR(10),
@NOMBRE VARCHAR(30),
@DIRECCION VARCHAR(30),
@CIUDAD_RESIDENCIA VARCHAR(30),
@CODIGO_LINEA VARCHAR(10),
@COD_USUARIO INT,
@TELEFONO VARCHAR(20)
AS
BEGIN
	INSERT INTO tblPILOTO(ID, NOMBRE, DIRECCION,CIUDAD_RESIDENCIA, CODIGO_LINEA, COD_USUARIO, TELEFONO) VALUES(@ID, @NOMBRE, @DIRECCION,@CIUDAD_RESIDENCIA, @CODIGO_LINEA, @COD_USUARIO, @TELEFONO)

		SELECT '1' AS SW,
			   'Registro creado correctamente'
END
GO

CREATE PROCEDURE SP_CrearAvion
@CODIGO VARCHAR(10),
@MODELO VARCHAR(20),
@CAPACIDAD INT,
@CODIGO_LINEA VARCHAR(10)
AS
BEGIN
	INSERT INTO tblAVION(CODIGO,MODELO,CAPACIDAD,CODIGO_LINEA) VALUES(@CODIGO,@MODELO,@CAPACIDAD,@CODIGO_LINEA)

		SELECT '1' AS SW,
			   'Registro creado correctamente'
END
GO

CREATE PROCEDURE SP_CrearAeropuerto
@CODIGO VARCHAR(10),
@NOMBRE VARCHAR(30),
@CIUDAD VARCHAR(30),
@PAIS VARCHAR(30),
@ID_RESPONSABLE VARCHAR(10),
@ESTADO VARCHAR(50)
AS
BEGIN
	INSERT INTO tblAEROPUERTO(CODIGO,NOMBRE,CIUDAD,PAIS,ID_RESPONSABLE,ESTADO) VALUES(@CODIGO,@NOMBRE,@CIUDAD,@PAIS,@ID_RESPONSABLE,@ESTADO)

		SELECT '1' AS SW,
			   'Registro creado correctamente'
END
GO

CREATE PROCEDURE SP_CrearEscalaTecnica
@CODIGO VARCHAR(10),
@COD_AEROPUERTO VARCHAR(10)
AS
BEGIN
	INSERT INTO tblESCALA_TECNICA(CODIGO, COD_AEROPUERTO) VALUES(@CODIGO, @COD_AEROPUERTO)

		SELECT '1' AS SW,
			   'Registro creado correctamente'
END
GO

CREATE PROCEDURE SP_CrearVuelo
@CODIGO VARCHAR(10),
@FECHA_partida SMALLDATETIME,
@FECHA_llegada SMALLDATETIME,
@PLAZAS_VACIAS INT,
@IDPILOTO VARCHAR(10),
@COD_AVION VARCHAR(10)
AS
BEGIN
	INSERT INTO tblVUELO(CODIGO, FECHA_partida,FECHA_llegada,PLAZAS_VACIAS,IDPILOTO,COD_AVION) VALUES(@CODIGO, @FECHA_partida,@FECHA_llegada,@PLAZAS_VACIAS,@IDPILOTO,@COD_AVION)

		SELECT '1' AS SW,
			   'Registro creado correctamente'
END
GO

CREATE PROCEDURE SP_CrearPlanVuelo
@CODIGO VARCHAR(10),
@CODIGO_VUELO VARCHAR(10),
@CODIGO_LINEA VARCHAR(10),
@CODIGO_ESCALATECNICA VARCHAR(10),
@AEROPUERTO_PARTIDA VARCHAR(10),
@AEROPUERTO_DESTINO VARCHAR(10)
AS
BEGIN
	INSERT INTO tblPROGRAMA_VUELO(CODIGO,CODIGO_VUELO,CODIGO_LINEA,CODIGO_ESCALATECNICA,AEROPUERTO_PARTIDA,AEROPUERTO_DESTINO) VALUES(@CODIGO,@CODIGO_VUELO,@CODIGO_LINEA,@CODIGO_ESCALATECNICA,@AEROPUERTO_PARTIDA,@AEROPUERTO_DESTINO)

		SELECT '1' AS SW,
			   'Registro creado correctamente'
END
GO

CREATE PROCEDURE SP_ConsultarPersona
@NOMBRE VARCHAR(10)
AS
BEGIN
	SELECT *	   
	FROM tblPERSONA
	WHERE NOMBRE = @NOMBRE

END
GO

CREATE PROCEDURE SP_ValidarPersona (
@ID VARCHAR(10))
AS
BEGIN
	SELECT *	   
	FROM tblPERSONA
	WHERE ID = @ID
END
GO

CREATE PROCEDURE SP_ObtenerCodigoUsuario
@NOMBRE_USUARIO VARCHAR(10)
AS
BEGIN
	SELECT CODIGO_USUARIO
	FROM tblUSUARIO
	WHERE NOMBRE_USUARIO = @NOMBRE_USUARIO

END
GO

CREATE PROCEDURE SP_ConsultarAvion
@CODIGO VARCHAR(10)
AS
BEGIN
	SELECT *	   
	FROM tblAVION
	WHERE CODIGO = @CODIGO

END
GO

CREATE PROCEDURE SP_ConsultarLineaAerea
@CODIGO VARCHAR(10)
AS
BEGIN
	SELECT *	   
	FROM tblLINEA_AEREA
	WHERE CODIGO = @CODIGO

END
GO

CREATE PROCEDURE SP_ConsultarRol
@NOMBRE_USUARIO VARCHAR(10)
AS
BEGIN
	SELECT ROL_USUARIO	   
	FROM tblUSUARIO
	WHERE NOMBRE_USUARIO = @NOMBRE_USUARIO

END
GO

CREATE PROCEDURE SP_ConsultarAeropuerto
@CODIGO VARCHAR(10)
AS
BEGIN
	SELECT *	   
	FROM tblAEROPUERTO
	WHERE CODIGO = @CODIGO

END
GO

CREATE PROCEDURE SP_ConsultarEscalaTecnica
@CODIGO VARCHAR(10)
AS
BEGIN
	SELECT *	   
	FROM tblESCALA_TECNICA
	WHERE CODIGO = @CODIGO

END
GO

CREATE PROCEDURE SP_ConsultarPiloto
@ID VARCHAR(10)
AS
BEGIN
	SELECT *	   
	FROM tblPILOTO
	WHERE ID = @ID

END
GO

CREATE PROCEDURE SP_ConsultarVuelo
@CODIGO VARCHAR(10)
AS
BEGIN
	SELECT *	   
	FROM tblVUELO
	WHERE CODIGO = @CODIGO

END
GO


CREATE PROCEDURE SP_ConsultarPlanVuelo
@CODIGO VARCHAR(10)
AS
BEGIN
	SELECT *	   
	FROM tblPROGRAMA_VUELO
	WHERE CODIGO = @CODIGO

END
GO




/*******------------------------------ PRUEBAS------------------------------*******/
INSERT INTO tblUsuario VALUES ('sebas','1','A')
INSERT INTO tblLINEA_AEREA VALUES ('1','LA','COLOMBIA')

exec SP_CrearUsuario @NOMBRE_USUARIO = 'piloto', @CLAVE_USUARIO='1', @ROL_USUARIO='P'

exec SP_CrearPersona @ID='1111', @NOMBRE='El Responsable', @CIUDAD = 'Medellín',@COD_USUARIO='1'


exec SP_CrearPiloto @ID = '1', @NOMBRE = 'DonPiloto', @DIRECCION = 'Cra 10',@CIUDAD_RESIDENCIA = 'Medellín', @CODIGO_LINEA = '1', @COD_USUARIO = 2 , @TELEFONO = '2341672'

exec SP_CrearAeropuerto @CODIGO = 'AB12',@NOMBRE = 'Olaya Herrera',@CIUDAD= 'Medellín',@PAIS='Colombia',@ID_RESPONSABLE='1',@ESTADO='ACTIVO'

exec SP_CrearEscalaTecnica @CODIGO = 'N/A', @COD_AEROPUERTO = null

select * from tblvuelo



